### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by simonspa** [simonspa/allpix-squared#60]
In gitlab by @Koensw on Jul 21, 2017, 16:34

We are almost at the stage to tag the first release @all :) I created a milestone v0.3 [here](https://gitlab.cern.ch/simonspa/allpix-squared/milestones/3) but unfortunately you cannot discuss a milestone directly so that why I bringing it up here. This milestone v0.3 can just as well be v1.0 I think.

Only missing things I can think of are:
* First version of the website (linked in the README.md) with the documentation and a short introduction. This will be done in !31 by @simonspa.
* Small improvements to the simulation chain. Mostly handled in !32 by @simonspa. There are also a few small changes discussed in #48.
* Fully working version of the TCAD converter. Will be implemented by @mvicente in !30.
* Check of the remaining detector models shipped in the framework. Here I still need some help, see #54.
* Final check if the simulation output is reasonable (and we did not introduce major bugs in the last commits :)). Probably I can do this mostly, but some help will be welcome. Some reference output will be nice (Can you send me some configs you have @schuetzepaul if that is not too much trouble?)

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jul 21, 2017, 16:36

@smaqbool You also made a small change to the RCEWriter right? This can also be included of course if you send a merge request

**Comment by simonspa** [comment]
In gitlab by @Koensw on Jul 21, 2017, 16:46

Oh and checking the latest version of the [allpix-manual.pdf](/uploads/d9e0f1fc4f815eff99711a23d1019e79/allpix-manual.pdf) would also be nice. If you are going to have a look at the manual @mvicente, please use this one. If you find some errors or things that are unclear I would be happy to hear it :)

**Comment by simonspa** [comment]
In gitlab by @simonspa on Jul 21, 2017, 17:14

@Koensw hold your horses, I still have a few things to discuss, also with @dhynds on Monday. E.g. is !32  not as simple as one might think, at least not from the physics side.

This does obviously not mean, we cannot continue discussing missing items.

**Comment by simonspa** [comment]
In gitlab by @simonspa on Jul 24, 2017, 17:06

open tasks:

## Framework/functionality

* [ ] Make sure #54 is fully implemented
* [ ] Discuss and implement defaults for physics (#48 )
* [ ] Merge !35 by @nurnberg as this will be nice for advertising

## Documentation

* [ ] Finalize documentation for the release (include bug fix #61 )
* [ ] Improve main README.md file, add license information for packages
* [ ] Add CONTRIBUTING.md
* [ ] Fill website with content
* [ ] Add documentation/website/... license: (cc)(-by)

## Physics

* [ ] Comparison with Timepix simulation & data
  * For simplicity use MCTruth information to circumvent tracking, add telescope resolution of ~5um
  * Probably a hand-cooked (deep fried) ROOT script should be enough for some cluster analysis
  * Potentially look at bias scan data
* [ ] Look at different outputs for different pixel implant sizes
  * requires implant implementation (see #65 )
  * requires finishing of !30 for conversion
  * ask @nurnberg if he could provide us with two different timepix sensor simulations (efields)
